# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31e3470537883cc4bc67ea78786f9ec0b46ce15e54ce497ff31fd7081dcc5544b3e3e9441fd1c37bc3cbdbb7c105d9553d3c59eb580655215d4aa8d527b09390

test:
  secret_key_base: abbb180a5cdd43e48bb1bfe56897101f414aba7dd3bdbe021f0cdce918b22b8ad6e936097e79f2fb3d269166125f23f3c17178f8d6c0b97995082ce695725952

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
